### ISSUE TITLE
GTScan not run in kali linux

### ISSUE THREAD

**Issue by guyhhu** [SigPloiter/GTScan#4]
![screenshot from 2018-08-04 21-05-44](https://user-images.githubusercontent.com/42042093/43682540-9b0cce12-982c-11e8-8c9e-849960605c61.png)
I was install python 3+,pip 3 and 
pyfiglet==0.7.5
termcolor==1.1.0
colorama==0.3.9
But still I face This Problem.........Please A proper solution.......

**Comment by SigPloiter** [comment]
did you apply the below

pip3 install -r requirements.txt ??

**Comment by guyhhu** [comment]
Yes.I did it....But New Problem....
![lll](https://user-images.githubusercontent.com/42042093/43876539-6320ad68-9b4a-11e8-981c-05f9d99dd794.png)

**Comment by SigPloiter** [comment]
Please make sure that the default python version to run is python3 not
python2 you can change that from the alternatives

**Comment by guyhhu** [comment]
Done....But problem not solve
![screenshot from 2018-08-08 11-19-44](https://user-images.githubusercontent.com/42042093/43897768-ffb3a03a-9b91-11e8-9f57-7fd4342576fa.png)

**Comment by guyhhu** [comment]
Done.But Problem not solve........Please give a solution.....
![screenshot from 2018-08-09 08-00-10](https://user-images.githubusercontent.com/42042093/43899525-160fc7f0-9b97-11e8-8eaa-b430560d01d5.png)

**Comment by SigPloiter** [comment]
please send the error you get now

**Comment by guyhhu** [comment]
root@kali:~/Desktop/GTScan-master# ./GTScan.py
Traceback (most recent call last):
  File "./GTScan.py", line 38, in <module>
    from colorama import init
ImportError: No module named 'colorama'
root@kali:~/Desktop/GTScan-master#


I have many problem in SigPloit ss7 attack.....can i get your email......or Social network
my email-horakrishna3@gmail.com

**Comment by guyhhu** [comment]
root@kali:~/Desktop/GTScan-master# ./GTScan.py
Traceback (most recent call last):
  File "./GTScan.py", line 38, in <module>
    from colorama import init
ImportError: No module named 'colorama'
root@kali:~/Desktop/GTScan-master#


I have many problem in SigPloit ss7 attack.....can i get your email......or Social network
my email-horakrishna3@gmail.com

**Comment by guyhhu** [comment]
root@kali:/Desktop/GTScan-master# ./GTScan.py
Traceback (most recent call last):
  File "./GTScan.py", line 38, in <module>
    from colorama import init
ImportError: No module named 'colorama'
root@kali:/Desktop/GTScan-master#


I have many problem in SigPloit ss7 attack.....can i get your email......or Social network
my email-horakrishna3@gmail.com

**Comment by jbdu94** [comment]
@guyhhu : it says "no module named colorama", so please do "`pip install colorama`" :)
Check this out: [https://pypi.org/project/colorama]
It worked fine for me
